import type {
  Brand,
  CashShift,
  InventoryMovement,
  Liquidation,
  Piece,
  Reservation,
  Sale,
  User,
} from "./types";

const today = () => new Date().toISOString();
const daysAgo = (n: number) =>
  new Date(Date.now() - n * 86400000).toISOString();

export const seedUsers: User[] = [
  { id: "u1", name: "Jorge Ikpali", role: "admin", active: true },
  { id: "u2", name: "Nath", role: "manager", active: true },
  { id: "u3", name: "Mariana", role: "empleado", active: true },
  { id: "u4", name: "Diego", role: "empleado", active: true },
];

export const seedBrands: Brand[] = [
  {
    id: "b1",
    name: "Taller Lú",
    contact: "Luisa Mendoza",
    phone: "55 1234 5678",
    instagram: "@tallerlu",
    brandPct: 65,
    pisoPct: 35,
    model: "consignacion",
    status: "activa",
    notes: "Cerámica de alta temperatura, Tlaxcala.",
    createdAt: daysAgo(120),
  },
  {
    id: "b2",
    name: "Estudio Casa Norte",
    contact: "Andrés Cobo",
    phone: "55 9876 5432",
    instagram: "@casanorte.mx",
    brandPct: 65,
    pisoPct: 35,
    model: "consignacion",
    status: "activa",
    createdAt: daysAgo(95),
  },
  {
    id: "b3",
    name: "Heliotropo",
    contact: "Renata Quiroz",
    instagram: "@heliotropo.estudio",
    brandPct: 60,
    pisoPct: 40,
    model: "consignacion",
    status: "activa",
    notes: "Textiles teñidos a mano.",
    createdAt: daysAgo(80),
  },
  {
    id: "b4",
    name: "Bárbara Sánchez",
    contact: "Bárbara Sánchez",
    instagram: "@b.sanchez.obra",
    brandPct: 70,
    pisoPct: 30,
    model: "consignacion",
    status: "activa",
    createdAt: daysAgo(60),
  },
  {
    id: "b5",
    name: "Roma Ediciones",
    contact: "Pablo Aristi",
    instagram: "@romaediciones",
    brandPct: 55,
    pisoPct: 45,
    model: "compra_directa",
    status: "activa",
    createdAt: daysAgo(45),
  },
  {
    id: "b6",
    name: "Ikpali Studio",
    contact: "Jorge Ikpali",
    brandPct: 100,
    pisoPct: 0,
    model: "pieza_propia",
    status: "activa",
    notes: "Piezas propias del estudio.",
    createdAt: daysAgo(200),
  },
];

export const seedPieces: Piece[] = [
  {
    id: "p1",
    name: "Tazón anillo",
    brandId: "b1",
    category: "ceramica",
    shortDescription: "Tazón bajo, esmaltado mate.",
    curatorialNote: "Dialoga con la torre 02 y la cesta 04.",
    material: "Gres",
    dimensions: "18 × 18 × 7 cm",
    imageIdx: 1,
    price: 1450,
    brandPct: 65,
    pisoPct: 35,
    initialStock: 3,
    currentStock: 3,
    isUnique: false,
    isConsignment: true,
    status: "en_piso",
    location: "Mesa B",
    entryDate: daysAgo(40),
    reviewDate: daysAgo(-20),
    receivedBy: "Nath",
    createdAt: daysAgo(40),
  },
  {
    id: "p2",
    name: "Lámpara torre 02",
    brandId: "b2",
    category: "iluminacion",
    shortDescription: "Lámpara de mesa en aluminio doblado.",
    material: "Aluminio anodizado",
    dimensions: "12 × 12 × 38 cm",
    imageIdx: 2,
    price: 4800,
    brandPct: 65,
    pisoPct: 35,
    initialStock: 1,
    currentStock: 1,
    isUnique: true,
    isConsignment: true,
    status: "en_piso",
    location: "Repisa A",
    entryDate: daysAgo(30),
    receivedBy: "Nath",
    createdAt: daysAgo(30),
  },
  {
    id: "p3",
    name: "Cesta disco",
    brandId: "b3",
    category: "textil",
    shortDescription: "Cesta tejida en sisal, base plana.",
    material: "Sisal natural",
    dimensions: "Ø 32 × 14 cm",
    imageIdx: 3,
    price: 1980,
    brandPct: 60,
    pisoPct: 40,
    initialStock: 2,
    currentStock: 2,
    isUnique: false,
    isConsignment: true,
    status: "en_piso",
    location: "Mesa A",
    entryDate: daysAgo(25),
    receivedBy: "Diego",
    createdAt: daysAgo(25),
  },
  {
    id: "p4",
    name: "Jarra ovoide",
    brandId: "b1",
    category: "ceramica",
    material: "Porcelana",
    dimensions: "10 × 10 × 24 cm",
    imageIdx: 4,
    price: 2200,
    brandPct: 65,
    pisoPct: 35,
    initialStock: 4,
    currentStock: 4,
    isUnique: false,
    isConsignment: true,
    status: "en_piso",
    location: "Vitrina",
    entryDate: daysAgo(60),
    receivedBy: "Nath",
    createdAt: daysAgo(60),
  },
  {
    id: "p5",
    name: "Pieza de muro · 01",
    brandId: "b4",
    category: "escultura",
    shortDescription: "Relieve cerámico, edición de autor.",
    curatorialNote: "Pieza única, firmada al reverso.",
    material: "Barro reducido",
    dimensions: "42 × 42 × 6 cm",
    imageIdx: 5,
    price: 8500,
    brandPct: 70,
    pisoPct: 30,
    initialStock: 1,
    currentStock: 1,
    isUnique: true,
    isConsignment: true,
    status: "en_piso",
    location: "Muro norte",
    entryDate: daysAgo(15),
    receivedBy: "Jorge Ikpali",
    createdAt: daysAgo(15),
  },
  {
    id: "p6",
    name: "Vela columna",
    brandId: "b6",
    category: "vela",
    material: "Cera de soya",
    dimensions: "6 × 6 × 18 cm",
    imageIdx: 6,
    price: 480,
    brandPct: 100,
    pisoPct: 0,
    initialStock: 12,
    currentStock: 10,
    isUnique: false,
    isConsignment: false,
    status: "en_piso",
    location: "Mesa caja",
    entryDate: daysAgo(50),
    receivedBy: "Mariana",
    createdAt: daysAgo(50),
  },
  {
    id: "p7",
    name: "Libro · objeto doméstico mexicano",
    brandId: "b5",
    category: "editorial",
    material: "Papel offset, tapa dura",
    dimensions: "21 × 28 × 2 cm",
    imageIdx: 7,
    price: 760,
    brandPct: 55,
    pisoPct: 45,
    initialStock: 6,
    currentStock: 5,
    isUnique: false,
    isConsignment: false,
    status: "en_piso",
    location: "Mesa central",
    entryDate: daysAgo(20),
    receivedBy: "Diego",
    createdAt: daysAgo(20),
  },
  {
    id: "p8",
    name: "Tazón pequeño",
    brandId: "b1",
    category: "ceramica",
    material: "Gres esmaltado",
    dimensions: "12 × 12 × 5 cm",
    imageIdx: 8,
    price: 680,
    brandPct: 65,
    pisoPct: 35,
    initialStock: 8,
    currentStock: 6,
    isUnique: false,
    isConsignment: true,
    status: "en_piso",
    location: "Mesa B",
    entryDate: daysAgo(38),
    receivedBy: "Nath",
    createdAt: daysAgo(38),
  },
  {
    id: "p9",
    name: "Cesta torre",
    brandId: "b3",
    category: "textil",
    material: "Sisal teñido",
    dimensions: "Ø 24 × 48 cm",
    imageIdx: 3,
    price: 3400,
    brandPct: 60,
    pisoPct: 40,
    initialStock: 1,
    currentStock: 0,
    isUnique: true,
    isConsignment: true,
    status: "vendida",
    location: "—",
    entryDate: daysAgo(70),
    receivedBy: "Nath",
    createdAt: daysAgo(70),
  },
  {
    id: "p10",
    name: "Lámpara disco",
    brandId: "b2",
    category: "iluminacion",
    material: "Acero pintado",
    dimensions: "Ø 28 × 10 cm",
    imageIdx: 2,
    price: 5200,
    brandPct: 65,
    pisoPct: 35,
    initialStock: 1,
    currentStock: 1,
    isUnique: true,
    isConsignment: true,
    status: "en_piso",
    location: "Esquina sur",
    entryDate: daysAgo(8),
    receivedBy: "Nath",
    createdAt: daysAgo(8),
  },
  {
    id: "p11",
    name: "Jarra cilindro",
    brandId: "b1",
    category: "ceramica",
    material: "Gres",
    dimensions: "9 × 9 × 28 cm",
    imageIdx: 4,
    price: 1850,
    brandPct: 65,
    pisoPct: 35,
    initialStock: 3,
    currentStock: 1,
    isUnique: false,
    isConsignment: true,
    status: "reservada",
    location: "Vitrina",
    entryDate: daysAgo(55),
    receivedBy: "Mariana",
    createdAt: daysAgo(55),
  },
  {
    id: "p12",
    name: "Objeto cestería pequeño",
    brandId: "b3",
    category: "objeto",
    material: "Fibra natural",
    dimensions: "14 × 14 × 8 cm",
    imageIdx: 1,
    price: 920,
    brandPct: 60,
    pisoPct: 40,
    initialStock: 4,
    currentStock: 4,
    isUnique: false,
    isConsignment: true,
    status: "en_piso",
    location: "Mesa A",
    entryDate: daysAgo(95),
    receivedBy: "Nath",
    createdAt: daysAgo(95),
  },
];

// Demo: a couple of sales already in history, one cash + one card
const _saleItem = (
  piece: Piece,
  qty: number
): {
  pieceId: string;
  pieceName: string;
  brandId: string;
  brandName: string;
  qty: number;
  unitPrice: number;
  brandPct: number;
  pisoPct: number;
  brandAmount: number;
  pisoAmount: number;
  lineTotal: number;
} => {
  const lineTotal = piece.price * qty;
  return {
    pieceId: piece.id,
    pieceName: piece.name,
    brandId: piece.brandId,
    brandName: seedBrands.find((b) => b.id === piece.brandId)!.name,
    qty,
    unitPrice: piece.price,
    brandPct: piece.brandPct,
    pisoPct: piece.pisoPct,
    brandAmount: Math.round((lineTotal * piece.brandPct) / 100),
    pisoAmount: Math.round((lineTotal * piece.pisoPct) / 100),
    lineTotal,
  };
};

export const seedSales: Sale[] = [
  {
    id: "s1",
    folio: "PI-000142",
    userId: "u3",
    userName: "Mariana",
    items: [_saleItem(seedPieces[8], 1)], // cesta torre — pieza única
    total: 3400,
    paymentMethod: "tarjeta",
    status: "completada",
    createdAt: daysAgo(2),
  },
  {
    id: "s2",
    folio: "PI-000143",
    userId: "u4",
    userName: "Diego",
    items: [_saleItem(seedPieces[5], 2), _saleItem(seedPieces[6], 1)], // velas + libro
    total: 480 * 2 + 760,
    paymentMethod: "efectivo",
    cashReceived: 2000,
    change: 2000 - (480 * 2 + 760),
    status: "completada",
    createdAt: daysAgo(1),
  },
  {
    id: "s3",
    folio: "PI-000144",
    userId: "u3",
    userName: "Mariana",
    items: [_saleItem(seedPieces[7], 2)], // tazón pequeño x2
    total: 1360,
    paymentMethod: "efectivo",
    cashReceived: 1500,
    change: 140,
    status: "completada",
    createdAt: today(),
  },
];

export const seedMovements: InventoryMovement[] = seedPieces.flatMap((p) => {
  const arr: InventoryMovement[] = [
    {
      id: `mv-init-${p.id}`,
      pieceId: p.id,
      pieceName: p.name,
      brandId: p.brandId,
      type: "entrada",
      reason: "nueva_consignacion",
      qty: p.initialStock,
      stockBefore: 0,
      stockAfter: p.initialStock,
      userId: "u2",
      userName: "Nath",
      createdAt: p.entryDate,
    },
  ];
  return arr;
});

export const seedReservations: Reservation[] = [
  {
    id: "r1",
    pieceId: "p11",
    pieceName: "Jarra cilindro",
    customerName: "Ana Tafolla",
    customerContact: "55 1212 3434",
    qty: 1,
    reservedBy: "Mariana",
    reservedAt: daysAgo(3),
    expiresAt: daysAgo(-4),
    status: "activa",
    note: "Pasa el viernes a recoger.",
  },
];

export const seedShifts: CashShift[] = [
  {
    id: "sh1",
    openedBy: "u3",
    openedByName: "Mariana",
    openedAt: new Date(
      new Date().setHours(10, 0, 0, 0)
    ).toISOString(),
    openingCash: 1500,
    status: "abierta",
  },
];

export const seedLiquidations: Liquidation[] = [];
